trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: SolutionBaseName
  value: SFA.DAS.OnBoardingTool.Functions
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: RELEASE Management Resources
- group: RELEASE das-onboarding

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.0
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.4
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)

- stage: Deploy_PRD
  dependsOn: Build
  displayName: Deploy to PRD
  variables:
  - group: Prod Management Resources
  - group: Prod Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PROD
      ServiceConnection: SFA-DIG-Prod-ARM